---
image: docker:latest
services:
    - docker:dind

before_script:
    - apk update && apk add --no-cache
        python3-dev py3-pip gcc git curl build-base
        autoconf automake py3-cryptography linux-headers
        musl-dev libffi-dev openssl-dev openssh tree findutils
    - pwd
    - 'echo "CI_PROJECT_DIR: $CI_PROJECT_DIR, \
       CI_BUILDS_DIR: $CI_BUILDS_DIR"'
    - allFiles=`find . -maxdepth 1 -mindepth 1  -not -name '.git' -printf '%p '`
    - mkdir selenium
    - cp -avr $allFiles selenium/
    - tree -a    
    - docker info
    - python3 --version
    - python3 -m pip install ansible molecule[docker]
    - ansible --version
    - molecule --version

molecule:
    stage: test
    script:
        - ANSIBLE_ROLES_PATH="$CI_PROJECT_DIR:$ANSIBLE_ROLES_PATH"
        - cd selenium
        - molecule --debug test    
